server:
  port: 9000
spring:
  application:
    name: client-service

  security:
    oauth2:
      client:
        registration:
          client-service:
            provider: keycloak
            client-id: client-service
            client-secret: gykGrpib1pfbLYZ4azCynEw8nCEJ5Slr
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
